### PR TITLE
Allow for the disabling of prometheus metrics

### LINKED ISSUE #945: Allow dialing down of Prometheus metrics
Having a histogram, summary and counter around every endpoint can be costly in terms of metrics points and some people may wish to turn that down.

This feature allows turning off the per API endpoint metrics but keeps the response code summaries so alerting can be done if 4xx or 5xx start turning up.

### PR DESCRIPTION
**Pull request by rvowles**
Fixes #945

### CODE REVIEW

**Comment by rvowles** [comment]
Waiting on the new artifact to reach Central

**Comment by nimblenitin** [comment]
@rvowles after upgrading to 1.6.1 the metric edge_poll_api_histogram_bucket is unavailable. We need this metric to define slo. Can you let me know if this is a bug?

**Comment by rvowles** [comment]
Can you try setting `prometheus.jersey.none=false` in your config? If that works, then yes its a bug with a workaround. If not, then I will need to do a new release!

**Comment by nimblenitin** [comment]
tried setting the env, it didn't work, please let me know if I can help to bring back the metric.

**Comment by rvowles** [comment]
heya @nimblenitin - could you give me a bit more info? are you running it as different pieces? do you have the configuration on the edge service? I have just checked and its definitely there when I set it

image

**Comment by nimblenitin** [comment]
yes we have deployed all 4 components separately as a helm chart, below is what i tried setting in edge helm chart values's file:

```
edge:
  replicaCount: 3
  hpa:
    enabled: false
    maxReplicas: 6
  image:
    tag: 1.6.1
  environmentVars:
    prometheus.jersey.none: "true"

```

**Comment by nimblenitin** [comment]
this works had to set env value to false. thanks :)

**Comment by rvowles** [comment]
thanks for picking this up, I will fix it back to the default for the next release!

**Pull request merged**
